### PR TITLE
Add Microsoft Teams alerting provider

### PR DESCRIPTION
**Pull request by zeylos**
Hi there,

I added the Microsoft Teams alerting provider, the related tests and some sections on the README on how to use it.
I'm currently using it in a production environment.

I'm not a developer so please feel free to critize / edit stuff you don't like.

Thanks for your work,
Zeylos

### CODE REVIEW

**Comment by TwinProduction** [comment]
@zeylos If you're not a dev, you're putting a lot of devs to shame with this PR 🤣 
Beautifully done.

Could you resolve the conflicts? I'll merge it afterward.

**Comment by zeylos** [comment]
Lol, I'm a Kube and Linux admin so I guess I'm not that far from a dev but I never wrote in Go so thank you :p.

I resolved the conflict.

Have a good day

**Comment by TwinProduction** [comment]
@zeylos Thank you for your contribution!

**Comment by TwinProduction** [comment]
Released in [v2.8.1](https://github.com/TwinProduction/gatus/releases/tag/v2.8.1)

**Pull request merged**
