### PR TITLE
Add basic duration comparison

### LINKED ISSUE #39: Support for human-readable duration comparison
Some placeholders return durations, in milliseconds.

My proposal is to be able to compare durations with human-readable strings along with integers, such as `2 minutes` or `28 days`, which internally resolves to milliseconds.

The choice of supported formats is left for the implementation.

### PR DESCRIPTION
**Pull request by Exagone313**
Fix #39

### CODE REVIEW

**Comment by Exagone313** [comment]
@TwinProduction I added a patch for days, maybe it should be in another PR though

**Comment by Exagone313** [comment]
I don't know if the two `if` could be made as a single one, to avoid using `continue`. Feel free to amend my commit.

**Comment by TwinProduction** [comment]
@Exagone313 Would you mind creating a different PR for the implementation of days? 🙏

I prefer releasing v1.6.0 with just support for the default `time.ParseDuration(...)` and then looking at supporting days separately

**Comment by TwinProduction** [comment]
@Exagone313 I did a soft revert of the commit you made for supporting days so that you can create a different PR for that feature

**Comment by TwinProduction** [comment]
Released in [v1.6.0](https://github.com/TwinProduction/gatus/releases/tag/v1.6.0)

**Comment by Exagone313** [comment]
Ok, I should work on this during the week end.

**Pull request merged**
