### PR TITLE
Add Docker Compose example

### PR DESCRIPTION
**Pull request by 49e94b8f256530dc0d41f740dfe8a4c1**

### CODE REVIEW

**Comment by TwinProduction** [comment]
Hello @49e94b8f256530dc0d41f740dfe8a4c1,

An example for docker-compose is already present in the `example` folder, though it's an example of Gatus with Grafana and Prometheus.

While I'm not against having another one with only Gatus, could you please move it to the `example` folder too instead of the README?

**Comment by TwinProduction** [comment]
Would you mind also copying the `config.yaml` from the minimal folder and using that one instead of pointing to the one from the minimal example?

For the sake of consistency :)

**Comment by 49e94b8f256530dc0d41f740dfe8a4c1** [comment]
@TwinProduction,

I did as requested. Thank you.

**Comment by TwinProduction** [comment]
Thank you!

**Pull request merged**
